services:
  parabank:
    image: viorel4git/parasoft-parabank
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/parabank/index.htm"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 20s