[pytest]
pythonpath = .
markers =
    smoke: teste critice rapide
    regression: teste complete
    api: teste API
    ui: teste UI
    auth: teste care necesita autentificare
    form: teste de formulare
addopts = --screenshot only-on-failure --alluredir=my_allure_dir