Browser=Chromium
Environment=Local
Base_URL=http://localhost:8080/parabank/
Base_URL_API=http://localhost:8080/parabank/services/bank/
OS=Windows 10
Python=3.13.2
Pytest=9.0.2
Playwright=1.57.0
allure-pytest=2.36.0
